INSERT INTO TB_CATEGORY(DESCRIPTION) VALUES ('Curso');
INSERT INTO TB_CATEGORY(DESCRIPTION) VALUES ('Oficina');

INSERT INTO TB_PARTICIPANT(EMAIL, NAME) VALUES ('José Silva', 'jose@gmail.com');
INSERT INTO TB_PARTICIPANT(EMAIL, NAME) VALUES ('Thiago Faria', 'thiago@gmail.com');
INSERT INTO TB_PARTICIPANT(EMAIL, NAME) VALUES ('Maria do Rosário', 'maria@gmail.com');
INSERT INTO TB_PARTICIPANT(EMAIL, NAME) VALUES ('Teresa Silva', 'teresa@gmail.com');

INSERT INTO TB_ACTIVITY(NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('Curso de HTML', 'Aprenda HTML de forma prática', 80.0, 1);
INSERT INTO TB_ACTIVITY(NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('Oficina de Github', 'Controle versões de seus projetos', 50.0, 2);

INSERT INTO TB_BLOCK(START, FINISH, ACTIVITY_ID) VALUES (TIMESTAMP WITH TIME ZONE '2017-09-25T11:00:00Z', TIMESTAMP WITH TIME ZONE '2017-09-25T14:00:00Z', 1);
INSERT INTO TB_BLOCK(START, FINISH, ACTIVITY_ID) VALUES (TIMESTAMP WITH TIME ZONE '2017-09-25T17:00:00Z', TIMESTAMP WITH TIME ZONE '2017-09-25T21:00:00Z', 2);
INSERT INTO TB_BLOCK(START, FINISH, ACTIVITY_ID) VALUES (TIMESTAMP WITH TIME ZONE '2017-09-26T11:00:00Z', TIMESTAMP WITH TIME ZONE '2017-09-26T14:00:00Z', 2);

INSERT INTO TB_ACTIVITY_PARTICIPANT(ACTIVITY_ID, PARTICIPANT_ID) VALUES (1, 1);
INSERT INTO TB_ACTIVITY_PARTICIPANT(ACTIVITY_ID, PARTICIPANT_ID) VALUES (1, 2);
INSERT INTO TB_ACTIVITY_PARTICIPANT(ACTIVITY_ID, PARTICIPANT_ID) VALUES (1, 3);
INSERT INTO TB_ACTIVITY_PARTICIPANT(ACTIVITY_ID, PARTICIPANT_ID) VALUES (2, 1);
INSERT INTO TB_ACTIVITY_PARTICIPANT(ACTIVITY_ID, PARTICIPANT_ID) VALUES (2, 3);
INSERT INTO TB_ACTIVITY_PARTICIPANT(ACTIVITY_ID, PARTICIPANT_ID) VALUES (2, 4);
